### ISSUE TITLE
REC: 建议

### ISSUE THREAD

**Issue by HappyCodeHC** [class-tools/class-tools.github.io#1]
我认为官网里可以加上【工具下载】【更新日志】等板块，而不是一个博客
~~其实是我发出做官网的建议的，这个仓库也是我建的~~

**Comment by HappyCodeHC** [comment]
我认为可以参考 <https://cpeditor.org/>

**Comment by ren-yc** [comment]
> 我认为可以参考 https://cpeditor.org/

那么您会 HTML + CSS + JS 吗，我不是太擅长，如果您很擅长的话就您来做官网吧

**最好是全英文的**

**Comment by HappyCodeHC** [comment]
> > 我认为可以参考 https://cpeditor.org/
> 
> 那么您会 HTML + CSS + JS 吗，我不是太擅长，如果您很擅长的话就您来做官网吧
> 
> **最好是全英文的**

我会，实在不行可以去看[W3school](https://www.w3school.com.cn/)  
另外不需要英文吧，中文即可（说真的我英语特烂

**Comment by ren-yc** [comment]
> > > 我认为可以参考 https://cpeditor.org/
> > 
> > 
> > 那么您会 HTML + CSS + JS 吗，我不是太擅长，如果您很擅长的话就您来做官网吧
> > **最好是全英文的**
> 
> 我会，实在不行可以去看 [W3school](https://www.w3school.com.cn/) 另外不需要英文吧，中文即可（说真的我英语特烂

可以双语吗，搞个可以调语言的东西？

我不是特别清楚，如果不行的话那当我没说。

**Comment by HappyCodeHC** [comment]
> > > > 我认为可以参考 https://cpeditor.org/
> > > 
> > > 
> > > 那么您会 HTML + CSS + JS 吗，我不是太擅长，如果您很擅长的话就您来做官网吧
> > > **最好是全英文的**
> > 
> > 
> > 我会，实在不行可以去看 [W3school](https://www.w3school.com.cn/) 另外不需要英文吧，中文即可（说真的我英语特烂
> 
> 可以双语吗，搞个可以调语言的东西？
> 
> 我不是特别清楚，如果不行的话那当我没说。

可行，~~但不好实现~~

**Comment by ren-yc** [comment]
**目前本项目更换负责人为 @tigerchen-coder **
